apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer  # Change the service type to LoadBalancer
  ports:
  - name: "vote-service"
    port: 80  # Port exposed by the service
    targetPort: 5000  # Port that the application is listening on
  selector:
    app: vote