# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - worker/*
pool:
  name: self-hosted

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1785568d-e183-43cd-8eb9-bbb40f20afb0'
  imageRepository: 'Worker'
  containerRegistry: 'ncplcr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/worker/Dockerfile'
  tag: |
    $(Build.BuildId)
    latest


stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: default   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'worker/Dockerfile'
        tags: '$(tag)'
          
- stage: Push
  displayName: Push 
  jobs:
  - job: Push
    displayName: Push
    pool:
      name: default   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: Push
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Helm_install_and_package
  displayName: Helm install 
  jobs:
  - job: Helm
    displayName: Helm install
    pool:
      name: default   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true

    - task: HelmDeploy@0
      inputs:
        command: 'package'
        chartPath: '/home/ubuntu/myagent/_work/3/s/k8s-specifications/worker'

- stage: Artifact
  displayName: Artifact 
  jobs:
  - job: Artifact
    displayName: Artifact
    pool:
      name: default   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '/home/ubuntu/myagent/_work/3/s/k8s-specifications/worker'
        artifact: 'helm-worker'
        publishLocation: 'pipeline'