# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - worker/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1785568d-e183-43cd-8eb9-bbb40f20afb0'
  imageRepository: 'Worker'
  containerRegistry: 'ncplcr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/worker/Dockerfile'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  tag: |
    $(Build.BuildId)
    latest


stages:
- stage: sonarqube
  displayName: sonarqube 
  jobs:
  - job: sonarqube
    displayName: sonarqube
    pool:
     vmImage: $(vmImageName)   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'soanr-new'
        scannerMode: 'MSBuild'
        projectKey: 'azureworker'
        projectName: 'azureworker'
      
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    pool:
     vmImage: $(vmImageName)   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'worker/Dockerfile'
        tags: '$(tag)'
          
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: Push
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Helm_install_and_package
  displayName: Helm install 
  jobs:
  - job: Helm
    displayName: Helm install
    pool:
     vmImage: $(vmImageName)   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true

    - task: HelmDeploy@0
      inputs:
        command: 'package'
        chartPath: 'k8s-specifications/worker'
        chartVersion: '$(Build.BuildId)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'helm-worker'
        publishLocation: 'pipeline'