# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'Result'
  containerRegistry: 'ncplcr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  vmImageName: 'ubuntu-latest'
  tag: |
    $(Build.BuildId)
    latest


stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'ncplcr'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'result/Dockerfile'
        tags: '$(tag)'
          
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'ncplcr'
        repository: '$(imageRepository)'
        command: 'Push'
        tags: '$(tag)'

- stage: Helm_install_and_package
  displayName: Helm install 
  jobs:
  - job: Helm
    displayName: Helm install
    pool:
     vmImage: $(vmImageName)   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true

    - task: HelmDeploy@0
      inputs:
        command: 'package'
        chartPath: 'k8s-specifications/result'
        chartVersion: '$(Build.BuildId)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'helm-result'
        publishLocation: 'pipeline'