# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - vote/*
pool:
  name: self-hosted

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1785568d-e183-43cd-8eb9-bbb40f20afb0'
  imageRepository: 'microservice'
  containerRegistry: 'ncplcr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: 'Vote$(Build.BuildId)'

  # Agent VM image name
  pool:
  name: default

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: default   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'
          
- stage: Push
  displayName: Push 
  jobs:
  - job: Push
    displayName: Push
    pool:
      name: default   # Use a self-hosted agent
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: Push
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
