apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ncplcr.azurecr.io/app2:373
        ports:
        - containerPort: 8080