apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app_2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app_2
  template:
    metadata:
      labels:
        app: app_2
    spec:
      containers:
      - name: app_2
        image: ncplcr.azurecr.io/app2:379
        ports:
        - containerPort: 8080