apiVersion: v1
kind: Service
metadata:
  name: my-vote-service
spec:
  selector:
    app: my-vote  # Selector to match the pods targeted by this service
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 80  # Port on the pods
  type: LoadBalancer  # Exposes the service internally within the cluster