apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 5000  # Port that the application is listening on
  type: LoadBalancer  # Change the service type to LoadBalancer